[package]
name = "dumpspace-api"
version = "2.0.1"
edition = "2024"
description = "Compile-time offset resolution for Spuckwaffel's Dumpspace."
license = "MIT"
readme = "RUST_README.md"
repository = "https://github.com/B1Fr0st/dumpspace-api"

[workspace]
members = ["dumpspace-macros"]
default-members = [".", "dumpspace-macros"]

[dependencies]
dumpspace-macros = { version = "1.0.0", path = "dumpspace-macros" }
